// Generated from the legacy ddo-tools ddo.db `stats` table (238 rows). Ids are stable
// and referenced by the frontend, so append new stats; never renumber.

use crate::enums::StatCategory;

/// A stat the game tracks: an ability score, a save, a spell power, a skill, and so on.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Stat {
    pub id: i64,
    pub name: &'static str,
    pub category: StatCategory,
}

pub const STATS: &[Stat] = &[
    Stat { id: 1, name: "Strength", category: StatCategory::Ability },
    Stat { id: 2, name: "Dexterity", category: StatCategory::Ability },
    Stat { id: 3, name: "Constitution", category: StatCategory::Ability },
    Stat { id: 4, name: "Intelligence", category: StatCategory::Ability },
    Stat { id: 5, name: "Wisdom", category: StatCategory::Ability },
    Stat { id: 6, name: "Charisma", category: StatCategory::Ability },
    Stat { id: 7, name: "Melee Power", category: StatCategory::Martial },
    Stat { id: 8, name: "Ranged Power", category: StatCategory::Martial },
    Stat { id: 9, name: "Attack Bonus", category: StatCategory::Martial },
    Stat { id: 10, name: "Damage Bonus", category: StatCategory::Martial },
    Stat { id: 11, name: "Hit Points", category: StatCategory::Martial },
    Stat { id: 12, name: "Sneak Attack Dice", category: StatCategory::Martial },
    Stat { id: 13, name: "Armor Class", category: StatCategory::Defensive },
    Stat { id: 14, name: "Physical Resistance Rating", category: StatCategory::Defensive },
    Stat { id: 15, name: "Magical Resistance Rating", category: StatCategory::Defensive },
    Stat { id: 16, name: "Fortification", category: StatCategory::Defensive },
    Stat { id: 17, name: "Dodge", category: StatCategory::Defensive },
    Stat { id: 18, name: "Fortitude Save", category: StatCategory::Defensive },
    Stat { id: 19, name: "Reflex Save", category: StatCategory::Defensive },
    Stat { id: 20, name: "Will Save", category: StatCategory::Defensive },
    Stat { id: 21, name: "Spell Resistance", category: StatCategory::Defensive },
    Stat { id: 22, name: "Spell Points", category: StatCategory::Magical },
    Stat { id: 23, name: "Spell Penetration", category: StatCategory::Magical },
    Stat { id: 24, name: "Universal Spell Power", category: StatCategory::Magical },
    Stat { id: 25, name: "Fire Spell Power", category: StatCategory::Magical },
    Stat { id: 26, name: "Cold Spell Power", category: StatCategory::Magical },
    Stat { id: 27, name: "Electric Spell Power", category: StatCategory::Magical },
    Stat { id: 28, name: "Acid Spell Power", category: StatCategory::Magical },
    Stat { id: 29, name: "Sonic Spell Power", category: StatCategory::Magical },
    Stat { id: 30, name: "Light Spell Power", category: StatCategory::Magical },
    Stat { id: 31, name: "Force Spell Power", category: StatCategory::Magical },
    Stat { id: 32, name: "Negative Spell Power", category: StatCategory::Magical },
    Stat { id: 33, name: "Positive Spell Power", category: StatCategory::Magical },
    Stat { id: 34, name: "Repair Spell Power", category: StatCategory::Magical },
    Stat { id: 35, name: "Alignment Spell Power", category: StatCategory::Magical },
    Stat { id: 36, name: "Trip DC", category: StatCategory::Martial },
    Stat { id: 37, name: "Sunder DC", category: StatCategory::Martial },
    Stat { id: 38, name: "Stun DC", category: StatCategory::Martial },
    Stat { id: 39, name: "Assassinate DC", category: StatCategory::Martial },
    Stat { id: 40, name: "Helpless Damage", category: StatCategory::Martial },
    Stat { id: 41, name: "Balance", category: StatCategory::Skill },
    Stat { id: 42, name: "Bluff", category: StatCategory::Skill },
    Stat { id: 43, name: "Concentration", category: StatCategory::Skill },
    Stat { id: 44, name: "Diplomacy", category: StatCategory::Skill },
    Stat { id: 45, name: "Disable Device", category: StatCategory::Skill },
    Stat { id: 46, name: "Haggle", category: StatCategory::Skill },
    Stat { id: 47, name: "Heal", category: StatCategory::Skill },
    Stat { id: 48, name: "Hide", category: StatCategory::Skill },
    Stat { id: 49, name: "Intimidate", category: StatCategory::Skill },
    Stat { id: 50, name: "Jump", category: StatCategory::Skill },
    Stat { id: 51, name: "Listen", category: StatCategory::Skill },
    Stat { id: 52, name: "Move Silently", category: StatCategory::Skill },
    Stat { id: 53, name: "Open Lock", category: StatCategory::Skill },
    Stat { id: 54, name: "Perform", category: StatCategory::Skill },
    Stat { id: 55, name: "Repair", category: StatCategory::Skill },
    Stat { id: 56, name: "Search", category: StatCategory::Skill },
    Stat { id: 57, name: "Spellcraft", category: StatCategory::Skill },
    Stat { id: 58, name: "Spot", category: StatCategory::Skill },
    Stat { id: 59, name: "Swim", category: StatCategory::Skill },
    Stat { id: 60, name: "Tumble", category: StatCategory::Skill },
    Stat { id: 61, name: "Use Magic Device", category: StatCategory::Skill },
    Stat { id: 62, name: "Saving Throws vs Traps", category: StatCategory::Defensive },
    Stat { id: 63, name: "Seeker", category: StatCategory::Martial },
    Stat { id: 64, name: "Deadly", category: StatCategory::Martial },
    Stat { id: 65, name: "Accuracy", category: StatCategory::Martial },
    Stat { id: 66, name: "Deception", category: StatCategory::Martial },
    Stat { id: 67, name: "Speed", category: StatCategory::Martial },
    Stat { id: 68, name: "Doublestrike", category: StatCategory::Martial },
    Stat { id: 69, name: "Doubleshot", category: StatCategory::Martial },
    Stat { id: 70, name: "Physical Sheltering", category: StatCategory::Defensive },
    Stat { id: 71, name: "Magical Sheltering", category: StatCategory::Defensive },
    Stat { id: 72, name: "Concealment", category: StatCategory::Defensive },
    Stat { id: 73, name: "Healing Amplification", category: StatCategory::Other },
    Stat { id: 74, name: "Repair Amplification", category: StatCategory::Other },
    Stat { id: 75, name: "Well Rounded", category: StatCategory::Other },
    Stat { id: 76, name: "Fire Resistance", category: StatCategory::Defensive },
    Stat { id: 77, name: "Cold Resistance", category: StatCategory::Defensive },
    Stat { id: 78, name: "Electric Resistance", category: StatCategory::Defensive },
    Stat { id: 79, name: "Acid Resistance", category: StatCategory::Defensive },
    Stat { id: 80, name: "Sonic Resistance", category: StatCategory::Defensive },
    Stat { id: 81, name: "Light Resistance", category: StatCategory::Defensive },
    Stat { id: 82, name: "Force Resistance", category: StatCategory::Defensive },
    Stat { id: 83, name: "Negative Resistance", category: StatCategory::Defensive },
    Stat { id: 84, name: "Fire Absorption", category: StatCategory::Defensive },
    Stat { id: 85, name: "Cold Absorption", category: StatCategory::Defensive },
    Stat { id: 86, name: "Electric Absorption", category: StatCategory::Defensive },
    Stat { id: 87, name: "Acid Absorption", category: StatCategory::Defensive },
    Stat { id: 88, name: "Sonic Absorption", category: StatCategory::Defensive },
    Stat { id: 89, name: "Light Absorption", category: StatCategory::Defensive },
    Stat { id: 90, name: "Force Absorption", category: StatCategory::Defensive },
    Stat { id: 91, name: "Negative Absorption", category: StatCategory::Defensive },
    Stat { id: 92, name: "Abjuration Spell Focus", category: StatCategory::Magical },
    Stat { id: 93, name: "Conjuration Spell Focus", category: StatCategory::Magical },
    Stat { id: 94, name: "Enchantment Spell Focus", category: StatCategory::Magical },
    Stat { id: 95, name: "Evocation Spell Focus", category: StatCategory::Magical },
    Stat { id: 96, name: "Illusion Spell Focus", category: StatCategory::Magical },
    Stat { id: 97, name: "Necromancy Spell Focus", category: StatCategory::Magical },
    Stat { id: 98, name: "Transmutation Spell Focus", category: StatCategory::Magical },
    Stat { id: 99, name: "Wizardry", category: StatCategory::Magical },
    Stat { id: 100, name: "Spell Focus Mastery", category: StatCategory::Magical },
    Stat { id: 101, name: "Fire Spell Lore", category: StatCategory::Magical },
    Stat { id: 102, name: "Cold Spell Lore", category: StatCategory::Magical },
    Stat { id: 103, name: "Electric Spell Lore", category: StatCategory::Magical },
    Stat { id: 104, name: "Acid Spell Lore", category: StatCategory::Magical },
    Stat { id: 105, name: "Sonic Spell Lore", category: StatCategory::Magical },
    Stat { id: 106, name: "Light Spell Lore", category: StatCategory::Magical },
    Stat { id: 107, name: "Force Spell Lore", category: StatCategory::Magical },
    Stat { id: 108, name: "Negative Spell Lore", category: StatCategory::Magical },
    Stat { id: 109, name: "Positive Spell Lore", category: StatCategory::Magical },
    Stat { id: 110, name: "Repair Spell Lore", category: StatCategory::Magical },
    Stat { id: 111, name: "Universal Spell Lore", category: StatCategory::Magical },
    Stat { id: 112, name: "Spell Lore", category: StatCategory::Magical },
    Stat { id: 113, name: "Sacred Ground Lore", category: StatCategory::Magical },
    Stat { id: 114, name: "Dark Restoration Lore", category: StatCategory::Magical },
    Stat { id: 115, name: "Natural Armor", category: StatCategory::Defensive },
    Stat { id: 116, name: "Protection", category: StatCategory::Defensive },
    Stat { id: 117, name: "Sheltering", category: StatCategory::Defensive },
    Stat { id: 118, name: "Combat Mastery", category: StatCategory::Martial },
    Stat { id: 119, name: "Tendon Slice", category: StatCategory::Martial },
    Stat { id: 120, name: "Resistance", category: StatCategory::Defensive },
    Stat { id: 121, name: "Enchantment Save", category: StatCategory::Defensive },
    Stat { id: 122, name: "Curse Save", category: StatCategory::Defensive },
    Stat { id: 123, name: "Poison Resistance", category: StatCategory::Defensive },
    Stat { id: 124, name: "Nimble", category: StatCategory::Martial },
    Stat { id: 125, name: "Alluring", category: StatCategory::Martial },
    Stat { id: 126, name: "Rune Arm Spell Focus", category: StatCategory::Magical },
    Stat { id: 127, name: "Linguistics", category: StatCategory::Skill },
    Stat { id: 128, name: "Elemental Resistance", category: StatCategory::Defensive },
    Stat { id: 129, name: "Positive Healing Amplification", category: StatCategory::Other },
    Stat { id: 130, name: "Negative Healing Amplification", category: StatCategory::Other },
    Stat { id: 131, name: "Maximum Spell Points", category: StatCategory::Magical },
    Stat { id: 132, name: "Critical Damage Multiplier", category: StatCategory::Martial },
    Stat { id: 133, name: "Critical Threat Range", category: StatCategory::Martial },
    Stat { id: 134, name: "Melee and Ranged Power", category: StatCategory::Martial },
    Stat { id: 135, name: "Physical and Magical Resistance Rating", category: StatCategory::Defensive },
    Stat { id: 136, name: "Positive and Negative Spell Power", category: StatCategory::Magical },
    Stat { id: 137, name: "Positive and Negative Healing Amplification", category: StatCategory::Other },
    Stat { id: 138, name: "Doublestrike and Doubleshot", category: StatCategory::Martial },
    Stat { id: 140, name: "Poison Spell Power", category: StatCategory::Magical },
    Stat { id: 142, name: "Temporary Hit Points", category: StatCategory::Defensive },
    Stat { id: 143, name: "Bard Songs", category: StatCategory::Other },
    Stat { id: 144, name: "Movement Speed", category: StatCategory::Other },
    Stat { id: 145, name: "Maximum Hit Points", category: StatCategory::Defensive },
    Stat { id: 152, name: "Negative Energy Absorption", category: StatCategory::Defensive },
    Stat { id: 153, name: "Law Absorption", category: StatCategory::Defensive },
    Stat { id: 154, name: "Chaos Absorption", category: StatCategory::Defensive },
    Stat { id: 155, name: "Good Absorption", category: StatCategory::Defensive },
    Stat { id: 156, name: "Evil Absorption", category: StatCategory::Defensive },
    Stat { id: 157, name: "Elemental Absorption", category: StatCategory::Defensive },
    Stat { id: 158, name: "Alignment Absorption", category: StatCategory::Defensive },
    Stat { id: 159, name: "Spell Absorption", category: StatCategory::Defensive },
    Stat { id: 160, name: "Curse Absorption", category: StatCategory::Defensive },
    Stat { id: 161, name: "Saving Throws", category: StatCategory::Defensive },
    Stat { id: 162, name: "Universal Spell Focus", category: StatCategory::Magical },
    Stat { id: 163, name: "Breath Weapon Spell Focus", category: StatCategory::Magical },
    Stat { id: 164, name: "Shatter", category: StatCategory::Martial },
    Stat { id: 165, name: "Prudent", category: StatCategory::Martial },
    Stat { id: 166, name: "Astute", category: StatCategory::Martial },
    Stat { id: 167, name: "Negative Energy Resistance", category: StatCategory::Defensive },
    Stat { id: 170, name: "Illusion Save", category: StatCategory::Defensive },
    Stat { id: 171, name: "Fear Save", category: StatCategory::Defensive },
    Stat { id: 172, name: "Poison Save", category: StatCategory::Defensive },
    Stat { id: 173, name: "Disease Save", category: StatCategory::Defensive },
    Stat { id: 175, name: "Sleep Save", category: StatCategory::Defensive },
    Stat { id: 176, name: "Trap Save", category: StatCategory::Defensive },
    Stat { id: 177, name: "Spell Save", category: StatCategory::Defensive },
    Stat { id: 178, name: "Potency", category: StatCategory::Magical },
    Stat { id: 180, name: "Imbue Dice", category: StatCategory::Martial },
    Stat { id: 181, name: "Fortification Bypass", category: StatCategory::Martial },
    Stat { id: 182, name: "Attack Speed", category: StatCategory::Martial },
    Stat { id: 187, name: "Magical Resistance Rating Cap", category: StatCategory::Defensive },
    Stat { id: 188, name: "Threat Generation", category: StatCategory::Martial },
    Stat { id: 189, name: "Melee Threat Generation", category: StatCategory::Martial },
    Stat { id: 190, name: "Threat Reduction", category: StatCategory::Martial },
    Stat { id: 191, name: "Missile Deflection", category: StatCategory::Defensive },
    Stat { id: 192, name: "Offhand Strike Chance", category: StatCategory::Martial },
    Stat { id: 193, name: "Strikethrough", category: StatCategory::Martial },
    Stat { id: 194, name: "Critical Multiplier", category: StatCategory::Martial },
    Stat { id: 195, name: "Shield Armor Class", category: StatCategory::Defensive },
    Stat { id: 196, name: "Rune Arm DC", category: StatCategory::Magical },
    Stat { id: 198, name: "Tactics", category: StatCategory::Martial },
    Stat { id: 199, name: "Dodge Cap", category: StatCategory::Defensive },
    Stat { id: 200, name: "Critical Confirmation", category: StatCategory::Martial },
    Stat { id: 201, name: "Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 203, name: "Armor Class Percentage", category: StatCategory::Defensive },
    Stat { id: 204, name: "Sneak Attack Damage", category: StatCategory::Martial },
    Stat { id: 205, name: "Critical Damage", category: StatCategory::Martial },
    Stat { id: 206, name: "Spell Point Cost Reduction", category: StatCategory::Magical },
    Stat { id: 207, name: "Sneak Attack Hit", category: StatCategory::Martial },
    Stat { id: 209, name: "Spell DCs", category: StatCategory::Magical },
    Stat { id: 210, name: "Command", category: StatCategory::Skill },
    Stat { id: 211, name: "Persuasion", category: StatCategory::Skill },
    Stat { id: 212, name: "Universal Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 213, name: "Sneak Attack", category: StatCategory::Martial },
    Stat { id: 214, name: "Sneak Attack Bonus", category: StatCategory::Martial },
    Stat { id: 216, name: "Poison Spell Lore", category: StatCategory::Magical },
    Stat { id: 217, name: "Poison Absorption", category: StatCategory::Defensive },
    Stat { id: 218, name: "Chaos Spell Power", category: StatCategory::Magical },
    Stat { id: 219, name: "Chaos Spell Lore", category: StatCategory::Magical },
    Stat { id: 220, name: "Good Spell Power", category: StatCategory::Magical },
    Stat { id: 221, name: "Good Spell Lore", category: StatCategory::Magical },
    Stat { id: 222, name: "Evil Spell Power", category: StatCategory::Magical },
    Stat { id: 223, name: "Evil Spell Lore", category: StatCategory::Magical },
    Stat { id: 224, name: "Law Spell Power", category: StatCategory::Magical },
    Stat { id: 225, name: "Law Spell Lore", category: StatCategory::Magical },
    Stat { id: 226, name: "Melee and Ranged Threat Reduction", category: StatCategory::Martial },
    Stat { id: 227, name: "Ranged Threat Reduction", category: StatCategory::Martial },
    Stat { id: 228, name: "Saves vs Evil", category: StatCategory::Defensive },
    Stat { id: 229, name: "Attack and Damage vs Evil", category: StatCategory::Martial },
    Stat { id: 230, name: "Damage vs Evil", category: StatCategory::Martial },
    Stat { id: 231, name: "Critical Multiplier (19-20)", category: StatCategory::Martial },
    Stat { id: 232, name: "Unconsciousness Range", category: StatCategory::Defensive },
    Stat { id: 233, name: "Divination Spell Focus", category: StatCategory::Magical },
    Stat { id: 234, name: "Positive Absorption", category: StatCategory::Defensive },
    Stat { id: 235, name: "Repair Absorption", category: StatCategory::Defensive },
    Stat { id: 236, name: "Quality", category: StatCategory::Other },
    Stat { id: 237, name: "Caster Level", category: StatCategory::Magical },
    Stat { id: 238, name: "Maximum Caster Level", category: StatCategory::Magical },
    Stat { id: 239, name: "Max Dex Bonus (Armor)", category: StatCategory::Defensive },
    Stat { id: 240, name: "Max Dex Bonus (Shield)", category: StatCategory::Defensive },
    Stat { id: 241, name: "Ki", category: StatCategory::Other },
    Stat { id: 242, name: "Rage Uses", category: StatCategory::Other },
    Stat { id: 243, name: "Lay on Hands Uses", category: StatCategory::Other },
    Stat { id: 244, name: "Turn Undead Level", category: StatCategory::Other },
    Stat { id: 245, name: "Eldritch Blast Dice", category: StatCategory::Martial },
    Stat { id: 246, name: "Pact Dice", category: StatCategory::Martial },
    Stat { id: 247, name: "Spellsword Dice", category: StatCategory::Martial },
    Stat { id: 248, name: "Burning Ambition Dice", category: StatCategory::Martial },
    Stat { id: 249, name: "Fire Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 250, name: "Cold Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 251, name: "Electric Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 252, name: "Acid Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 253, name: "Sonic Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 254, name: "Light Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 255, name: "Force Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 256, name: "Negative Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 257, name: "Positive Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 258, name: "Repair Spell Critical Damage", category: StatCategory::Magical },
];
