use crate::enums::StatCategory;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Stat {
    pub id: i64,
    pub name: &'static str,
    pub category: StatCategory,
}

impl Stat {
    pub fn by_name(name: &str) -> Option<&'static Stat> {
        STATS.iter().find(|stat| stat.name == name)
    }
}

pub const STATS: &[Stat] = &[
    Stat { id: 1, name: "Strength", category: StatCategory::Ability },
    Stat { id: 2, name: "Dexterity", category: StatCategory::Ability },
    Stat { id: 3, name: "Constitution", category: StatCategory::Ability },
    Stat { id: 4, name: "Intelligence", category: StatCategory::Ability },
    Stat { id: 5, name: "Wisdom", category: StatCategory::Ability },
    Stat { id: 6, name: "Charisma", category: StatCategory::Ability },
    Stat { id: 7, name: "Melee Power", category: StatCategory::Martial },
    Stat { id: 8, name: "Ranged Power", category: StatCategory::Martial },
    Stat { id: 9, name: "Attack Bonus", category: StatCategory::Martial },
    Stat { id: 10, name: "Damage Bonus", category: StatCategory::Martial },
    Stat { id: 11, name: "Hit Points", category: StatCategory::Martial },
    Stat { id: 12, name: "Sneak Attack Dice", category: StatCategory::Martial },
    Stat { id: 13, name: "Armor Class", category: StatCategory::Defensive },
    Stat { id: 14, name: "Physical Resistance Rating", category: StatCategory::Defensive },
    Stat { id: 15, name: "Magical Resistance Rating", category: StatCategory::Defensive },
    Stat { id: 16, name: "Fortification", category: StatCategory::Defensive },
    Stat { id: 17, name: "Dodge", category: StatCategory::Defensive },
    Stat { id: 18, name: "Fortitude Save", category: StatCategory::Defensive },
    Stat { id: 19, name: "Reflex Save", category: StatCategory::Defensive },
    Stat { id: 20, name: "Will Save", category: StatCategory::Defensive },
    Stat { id: 21, name: "Spell Resistance", category: StatCategory::Defensive },
    Stat { id: 22, name: "Spell Points", category: StatCategory::Magical },
    Stat { id: 23, name: "Spell Penetration", category: StatCategory::Magical },
    Stat { id: 24, name: "Universal Spell Power", category: StatCategory::Magical },
    Stat { id: 25, name: "Fire Spell Power", category: StatCategory::Magical },
    Stat { id: 26, name: "Cold Spell Power", category: StatCategory::Magical },
    Stat { id: 27, name: "Electric Spell Power", category: StatCategory::Magical },
    Stat { id: 28, name: "Acid Spell Power", category: StatCategory::Magical },
    Stat { id: 29, name: "Sonic Spell Power", category: StatCategory::Magical },
    Stat { id: 30, name: "Light Spell Power", category: StatCategory::Magical },
    Stat { id: 31, name: "Force Spell Power", category: StatCategory::Magical },
    Stat { id: 32, name: "Negative Spell Power", category: StatCategory::Magical },
    Stat { id: 33, name: "Positive Spell Power", category: StatCategory::Magical },
    Stat { id: 34, name: "Repair Spell Power", category: StatCategory::Magical },
    Stat { id: 36, name: "Trip DC", category: StatCategory::Martial },
    Stat { id: 37, name: "Sunder DC", category: StatCategory::Martial },
    Stat { id: 38, name: "Stun DC", category: StatCategory::Martial },
    Stat { id: 39, name: "Assassinate DC", category: StatCategory::Martial },
    Stat { id: 40, name: "Helpless Damage", category: StatCategory::Martial },
    Stat { id: 41, name: "Balance", category: StatCategory::Skill },
    Stat { id: 42, name: "Bluff", category: StatCategory::Skill },
    Stat { id: 43, name: "Concentration", category: StatCategory::Skill },
    Stat { id: 44, name: "Diplomacy", category: StatCategory::Skill },
    Stat { id: 45, name: "Disable Device", category: StatCategory::Skill },
    Stat { id: 46, name: "Haggle", category: StatCategory::Skill },
    Stat { id: 47, name: "Heal", category: StatCategory::Skill },
    Stat { id: 48, name: "Hide", category: StatCategory::Skill },
    Stat { id: 49, name: "Intimidate", category: StatCategory::Skill },
    Stat { id: 50, name: "Jump", category: StatCategory::Skill },
    Stat { id: 51, name: "Listen", category: StatCategory::Skill },
    Stat { id: 52, name: "Move Silently", category: StatCategory::Skill },
    Stat { id: 53, name: "Open Lock", category: StatCategory::Skill },
    Stat { id: 54, name: "Perform", category: StatCategory::Skill },
    Stat { id: 55, name: "Repair", category: StatCategory::Skill },
    Stat { id: 56, name: "Search", category: StatCategory::Skill },
    Stat { id: 57, name: "Spellcraft", category: StatCategory::Skill },
    Stat { id: 58, name: "Spot", category: StatCategory::Skill },
    Stat { id: 59, name: "Swim", category: StatCategory::Skill },
    Stat { id: 60, name: "Tumble", category: StatCategory::Skill },
    Stat { id: 61, name: "Use Magic Device", category: StatCategory::Skill },
    Stat { id: 63, name: "Seeker", category: StatCategory::Martial },
    Stat { id: 64, name: "Deadly", category: StatCategory::Martial },
    Stat { id: 65, name: "Accuracy", category: StatCategory::Martial },
    Stat { id: 68, name: "Doublestrike", category: StatCategory::Martial },
    Stat { id: 69, name: "Doubleshot", category: StatCategory::Martial },
    Stat { id: 72, name: "Concealment", category: StatCategory::Defensive },
    Stat { id: 73, name: "Healing Amplification", category: StatCategory::Other },
    Stat { id: 74, name: "Repair Amplification", category: StatCategory::Other },
    Stat { id: 75, name: "Well Rounded", category: StatCategory::Other },
    Stat { id: 76, name: "Fire Resistance", category: StatCategory::Defensive },
    Stat { id: 77, name: "Cold Resistance", category: StatCategory::Defensive },
    Stat { id: 78, name: "Electric Resistance", category: StatCategory::Defensive },
    Stat { id: 79, name: "Acid Resistance", category: StatCategory::Defensive },
    Stat { id: 80, name: "Sonic Resistance", category: StatCategory::Defensive },
    Stat { id: 81, name: "Light Resistance", category: StatCategory::Defensive },
    Stat { id: 82, name: "Force Resistance", category: StatCategory::Defensive },
    Stat { id: 83, name: "Negative Resistance", category: StatCategory::Defensive },
    Stat { id: 84, name: "Fire Absorption", category: StatCategory::Defensive },
    Stat { id: 85, name: "Cold Absorption", category: StatCategory::Defensive },
    Stat { id: 86, name: "Electric Absorption", category: StatCategory::Defensive },
    Stat { id: 87, name: "Acid Absorption", category: StatCategory::Defensive },
    Stat { id: 88, name: "Sonic Absorption", category: StatCategory::Defensive },
    Stat { id: 89, name: "Light Absorption", category: StatCategory::Defensive },
    Stat { id: 90, name: "Force Absorption", category: StatCategory::Defensive },
    Stat { id: 91, name: "Negative Absorption", category: StatCategory::Defensive },
    Stat { id: 92, name: "Abjuration Focus", category: StatCategory::Magical },
    Stat { id: 93, name: "Conjuration Focus", category: StatCategory::Magical },
    Stat { id: 94, name: "Enchantment Focus", category: StatCategory::Magical },
    Stat { id: 95, name: "Evocation Focus", category: StatCategory::Magical },
    Stat { id: 96, name: "Illusion Focus", category: StatCategory::Magical },
    Stat { id: 97, name: "Necromancy Focus", category: StatCategory::Magical },
    Stat { id: 98, name: "Transmutation Focus", category: StatCategory::Magical },
    Stat { id: 101, name: "Fire Spell Lore", category: StatCategory::Magical },
    Stat { id: 102, name: "Cold Spell Lore", category: StatCategory::Magical },
    Stat { id: 103, name: "Electric Spell Lore", category: StatCategory::Magical },
    Stat { id: 104, name: "Acid Spell Lore", category: StatCategory::Magical },
    Stat { id: 105, name: "Sonic Spell Lore", category: StatCategory::Magical },
    Stat { id: 106, name: "Light Spell Lore", category: StatCategory::Magical },
    Stat { id: 107, name: "Force Spell Lore", category: StatCategory::Magical },
    Stat { id: 108, name: "Negative Spell Lore", category: StatCategory::Magical },
    Stat { id: 109, name: "Positive Spell Lore", category: StatCategory::Magical },
    Stat { id: 110, name: "Repair Spell Lore", category: StatCategory::Magical },
    Stat { id: 111, name: "Universal Spell Lore", category: StatCategory::Magical },
    Stat { id: 112, name: "Spell Lore", category: StatCategory::Magical },
    Stat { id: 113, name: "Sacred Ground Lore", category: StatCategory::Magical },
    Stat { id: 114, name: "Dark Restoration Lore", category: StatCategory::Magical },
    Stat { id: 121, name: "Enchantment Save", category: StatCategory::Defensive },
    Stat { id: 122, name: "Curse Save", category: StatCategory::Defensive },
    Stat { id: 123, name: "Poison Resistance", category: StatCategory::Defensive },
    Stat { id: 124, name: "Nimble", category: StatCategory::Martial },
    Stat { id: 125, name: "Alluring", category: StatCategory::Martial },
    Stat { id: 126, name: "Rune Arm Spell Focus", category: StatCategory::Magical },
    Stat { id: 127, name: "Linguistics", category: StatCategory::Skill },
    Stat { id: 128, name: "Elemental Resistance", category: StatCategory::Defensive },
    Stat { id: 129, name: "Positive Healing Amplification", category: StatCategory::Other },
    Stat { id: 130, name: "Negative Healing Amplification", category: StatCategory::Other },
    Stat { id: 133, name: "Critical Threat Range", category: StatCategory::Martial },
    Stat { id: 140, name: "Poison Spell Power", category: StatCategory::Magical },
    Stat { id: 142, name: "Temporary Hit Points", category: StatCategory::Defensive },
    Stat { id: 143, name: "Bard Songs", category: StatCategory::Other },
    Stat { id: 144, name: "Movement Speed", category: StatCategory::Other },
    Stat { id: 145, name: "Maximum Hit Points", category: StatCategory::Defensive },
    Stat { id: 153, name: "Law Absorption", category: StatCategory::Defensive },
    Stat { id: 154, name: "Chaos Absorption", category: StatCategory::Defensive },
    Stat { id: 155, name: "Good Absorption", category: StatCategory::Defensive },
    Stat { id: 156, name: "Evil Absorption", category: StatCategory::Defensive },
    Stat { id: 157, name: "Elemental Absorption", category: StatCategory::Defensive },
    Stat { id: 158, name: "Alignment Absorption", category: StatCategory::Defensive },
    Stat { id: 161, name: "Saving Throws", category: StatCategory::Defensive },
    Stat { id: 163, name: "Breath Weapon Spell Focus", category: StatCategory::Magical },
    Stat { id: 165, name: "Prudent", category: StatCategory::Martial },
    Stat { id: 166, name: "Astute", category: StatCategory::Martial },
    Stat { id: 170, name: "Illusion Save", category: StatCategory::Defensive },
    Stat { id: 171, name: "Fear Save", category: StatCategory::Defensive },
    Stat { id: 172, name: "Poison Save", category: StatCategory::Defensive },
    Stat { id: 173, name: "Disease Save", category: StatCategory::Defensive },
    Stat { id: 175, name: "Sleep Save", category: StatCategory::Defensive },
    Stat { id: 176, name: "Trap Save", category: StatCategory::Defensive },
    Stat { id: 177, name: "Spell Save", category: StatCategory::Defensive },
    Stat { id: 180, name: "Imbue Dice", category: StatCategory::Martial },
    Stat { id: 181, name: "Fortification Bypass", category: StatCategory::Martial },
    Stat { id: 187, name: "Magical Resistance Rating Cap", category: StatCategory::Defensive },
    Stat { id: 189, name: "Melee Threat Generation", category: StatCategory::Martial },
    Stat { id: 190, name: "Threat Reduction", category: StatCategory::Martial },
    Stat { id: 191, name: "Missile Deflection", category: StatCategory::Defensive },
    Stat { id: 192, name: "Offhand Strike Chance", category: StatCategory::Martial },
    Stat { id: 193, name: "Strikethrough", category: StatCategory::Martial },
    Stat { id: 194, name: "Critical Multiplier", category: StatCategory::Martial },
    Stat { id: 195, name: "Shield Armor Class", category: StatCategory::Defensive },
    Stat { id: 196, name: "Rune Arm DC", category: StatCategory::Magical },
    Stat { id: 199, name: "Dodge Cap", category: StatCategory::Defensive },
    Stat { id: 203, name: "Armor Class Percentage", category: StatCategory::Defensive },
    Stat { id: 204, name: "Sneak Attack Damage", category: StatCategory::Martial },
    Stat { id: 206, name: "Spell Point Cost Reduction", category: StatCategory::Magical },
    Stat { id: 207, name: "Sneak Attack Hit", category: StatCategory::Martial },
    Stat { id: 209, name: "Spell DCs", category: StatCategory::Magical },
    Stat { id: 212, name: "Universal Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 213, name: "Sneak Attack", category: StatCategory::Martial },
    Stat { id: 216, name: "Poison Spell Lore", category: StatCategory::Magical },
    Stat { id: 217, name: "Poison Absorption", category: StatCategory::Defensive },
    Stat { id: 218, name: "Chaos Spell Power", category: StatCategory::Magical },
    Stat { id: 219, name: "Chaos Spell Lore", category: StatCategory::Magical },
    Stat { id: 220, name: "Good Spell Power", category: StatCategory::Magical },
    Stat { id: 221, name: "Good Spell Lore", category: StatCategory::Magical },
    Stat { id: 222, name: "Evil Spell Power", category: StatCategory::Magical },
    Stat { id: 223, name: "Evil Spell Lore", category: StatCategory::Magical },
    Stat { id: 224, name: "Law Spell Power", category: StatCategory::Magical },
    Stat { id: 225, name: "Law Spell Lore", category: StatCategory::Magical },
    Stat { id: 227, name: "Ranged Threat Reduction", category: StatCategory::Martial },
    Stat { id: 231, name: "Critical Multiplier (19-20)", category: StatCategory::Martial },
    Stat { id: 232, name: "Unconsciousness Range", category: StatCategory::Defensive },
    Stat { id: 233, name: "Divination Focus", category: StatCategory::Magical },
    Stat { id: 237, name: "Caster Level", category: StatCategory::Magical },
    Stat { id: 238, name: "Maximum Caster Level", category: StatCategory::Magical },
    Stat { id: 239, name: "Max Dex Bonus (Armor)", category: StatCategory::Defensive },
    Stat { id: 241, name: "Ki", category: StatCategory::Other },
    Stat { id: 242, name: "Rage Uses", category: StatCategory::Other },
    Stat { id: 243, name: "Lay on Hands Uses", category: StatCategory::Other },
    Stat { id: 244, name: "Turn Undead Level", category: StatCategory::Other },
    Stat { id: 245, name: "Eldritch Blast Dice", category: StatCategory::Martial },
    Stat { id: 246, name: "Pact Dice", category: StatCategory::Martial },
    Stat { id: 247, name: "Spellsword Dice", category: StatCategory::Martial },
    Stat { id: 248, name: "Burning Ambition Dice", category: StatCategory::Martial },
    Stat { id: 249, name: "Fire Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 250, name: "Cold Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 251, name: "Electric Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 252, name: "Acid Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 253, name: "Sonic Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 254, name: "Light Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 255, name: "Force Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 256, name: "Negative Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 257, name: "Positive Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 258, name: "Repair Spell Critical Damage", category: StatCategory::Magical },
    Stat { id: 259, name: "Arcane Spell Failure", category: StatCategory::Magical },
    Stat { id: 260, name: "Arcane Spell Failure (Shield)", category: StatCategory::Magical },
    Stat { id: 261, name: "Armor Check Penalty", category: StatCategory::Defensive },
    Stat { id: 262, name: "Max Dex Bonus (Tower Shield)", category: StatCategory::Defensive },
    Stat { id: 263, name: "Displacement", category: StatCategory::Defensive },
    Stat { id: 264, name: "Incorporeality", category: StatCategory::Defensive },
    Stat { id: 265, name: "Dodge Bypass", category: StatCategory::Martial },
    Stat { id: 266, name: "Spell Threat Generation", category: StatCategory::Other },
    Stat { id: 267, name: "Ranged Threat Generation", category: StatCategory::Other },
    Stat { id: 268, name: "Rune Arm Charge Rate", category: StatCategory::Other },
    Stat { id: 269, name: "Point Blank Shot Range", category: StatCategory::Martial },
    Stat { id: 270, name: "Fate Points", category: StatCategory::Other },
    Stat { id: 271, name: "Turn Undead Uses", category: StatCategory::Other },
    Stat { id: 272, name: "Turn Undead Dice", category: StatCategory::Other },
    Stat { id: 273, name: "Turn Undead Max Dice", category: StatCategory::Other },
    Stat { id: 274, name: "Turn Undead Bonus", category: StatCategory::Other },
    Stat { id: 275, name: "Ki on Hit", category: StatCategory::Other },
    Stat { id: 276, name: "Ki on Critical", category: StatCategory::Other },
    Stat { id: 277, name: "Eldritch Blast d8 Dice", category: StatCategory::Magical },
    Stat { id: 278, name: "Empower Cost Reduction", category: StatCategory::Magical },
    Stat { id: 279, name: "Maximize Cost Reduction", category: StatCategory::Magical },
    Stat { id: 280, name: "Quicken Cost Reduction", category: StatCategory::Magical },
    Stat { id: 281, name: "Enlarge Cost Reduction", category: StatCategory::Magical },
    Stat { id: 282, name: "Heighten Cost Reduction", category: StatCategory::Magical },
    Stat { id: 283, name: "Extend Cost Reduction", category: StatCategory::Magical },
    Stat { id: 284, name: "Empower Healing Cost Reduction", category: StatCategory::Magical },
    Stat { id: 285, name: "Intensify Cost Reduction", category: StatCategory::Magical },
    Stat { id: 286, name: "Accelerate Cost Reduction", category: StatCategory::Magical },
    Stat { id: 287, name: "Eschew Materials Cost Reduction", category: StatCategory::Magical },
    Stat { id: 288, name: "Embolden Cost Reduction", category: StatCategory::Magical },
    Stat { id: 289, name: "Song Duration", category: StatCategory::Other },
    Stat { id: 290, name: "Song Armor Class", category: StatCategory::Other },
    Stat { id: 291, name: "Song Dodge", category: StatCategory::Other },
    Stat { id: 292, name: "Song Saving Throws", category: StatCategory::Other },
    Stat { id: 293, name: "Song Skills", category: StatCategory::Other },
    Stat { id: 294, name: "Song Physical Resistance Rating", category: StatCategory::Other },
    Stat { id: 295, name: "Song Universal Spell Power", category: StatCategory::Other },
    Stat { id: 296, name: "Song Healing Amplification", category: StatCategory::Other },
    Stat { id: 297, name: "Hireling Abilities", category: StatCategory::Other },
    Stat { id: 298, name: "Hireling Dodge", category: StatCategory::Other },
    Stat { id: 299, name: "Hireling Fortification", category: StatCategory::Other },
    Stat { id: 300, name: "Hireling Hit Points", category: StatCategory::Other },
    Stat { id: 301, name: "Hireling Magical Resistance Rating", category: StatCategory::Other },
    Stat { id: 302, name: "Hireling Melee Power", category: StatCategory::Other },
    Stat { id: 303, name: "Hireling Physical Resistance Rating", category: StatCategory::Other },
    Stat { id: 304, name: "Hireling Ranged Power", category: StatCategory::Other },
    Stat { id: 305, name: "Hireling Spell Power", category: StatCategory::Other },
    Stat { id: 306, name: "Action Boosts", category: StatCategory::Other },
    Stat { id: 307, name: "Melee Attack Speed", category: StatCategory::Martial },
    Stat { id: 308, name: "Ranged Attack Speed", category: StatCategory::Martial },
];
